# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lepth9VtUlPUip_9IYvBDVgLOIT6Ggov
"""

from flask import Flask, request, jsonify
import cv2
import numpy as np
from PIL import Image
import os
from io import BytesIO
from flask import render_template

# === Import your entire image analysis pipeline functions ===
from skin_analysis import analyze_image_all_regions  # You'll create this module

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/analyze', methods=['POST'])
def analyze():
    if 'image' not in request.files:
        return jsonify({'error': 'No image uploaded'}), 400

    file = request.files['image']
    image = Image.open(BytesIO(file.read())).convert("RGB")
    image_np = np.array(image)

    try:
        results = analyze_image_all_regions(image_np)
        return jsonify(results)
    except Exception as e:
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    import os
    port = int(os.environ.get("PORT", 5000))  # default to 5000 for local testing
    app.run(host='0.0.0.0', port=port)
